# Example P-matrix Modellings ----------------------------------------------------
# Inlcuding 'Reaction Norm Pictures'
# Including MCMC Models in .RData
# Including Centroid Shifting P-matrix visualisation


# Requires the following libraries ----------------------------------------------------

library(mvtnorm)
library(MASS)
library(MCMCglmm)

# load these .RData files ----
# they load the Gmatrices, the phentoypic data generated by them
# and the Bayesian MCMC models run analysing them as P-matrices
# ALL CODE TO DO THIS is provided below, commented out, after the fun stuff.

load('PhenCovVisualisation_4Jan18.RData')

# source the plotting script to make the P-matrix pictures ----
# also performs some analyses.
source('psb2.R')

# plot example 4.1 Trait x Env patterns ---
# it is a nice picture

# isolate the trait values
traits<-data.frame(data4.1[[1]][,23:32])

# choose colours and set margins (yes, it is BASE plotting....)
col2rgb(c("black","red","green","blue","yellow"))
par(mar=c(5,5,4,1))

# plot first trait without axes
plot(traits$trait1~rep(1,800), col=1, xlim=c(0.75,2.5), ylim=c(-12,12),
     axes=FALSE, ylab="Trait Value", xlab="Environment") 
axis(2) # add y axis
axis(1,at=c(1,2)) # add x-axis

# add clone means at jittered locations for E1
points(traits$trait2~rep(1.05,800),col=2,xlim=c(0,3))
points(traits$trait3~rep(1.1,800),col=3,xlim=c(0,3))
points(traits$trait4~rep(0.9,800),col=4,xlim=c(0,3))
points(traits$trait5~rep(0.95,800),col="yellow",xlim=c(0,3))

# add clone means at jittered locations for E2	
points(traits$trait6~rep(2,800),col=1,xlim=c(0,3))
points(traits$trait7~rep(2.05,800),col=2,xlim=c(0,3))
points(traits$trait8~rep(2.1,800),col=3,xlim=c(0,3))
points(traits$trait9~rep(1.9,800),col=4,xlim=c(0,3))
points(traits$trait10~rep(1.95,800),col="yellow",xlim=c(0,3))

# add lines between the dots
segments(rep(1,800),traits$trait1,rep(2,800),traits$trait6,rgb(0,0,0,0.2))
segments(rep(1.05,800),traits$trait2,rep(2.05,800),traits$trait7,rgb(1,0,0,0.1))
segments(rep(1.1,800),traits$trait3,rep(2.1,800),traits$trait8,rgb(0,1,0,0.1))
segments(rep(0.9,800),traits$trait4,rep(1.9,800),traits$trait9,rgb(0,0,1,0.2))
segments(rep(0.95,800),traits$trait5,rep(1.95,800),traits$trait10,rgb(1,1,0,0.1))

# Plotting the P-Matrices and Centroids and 'Shift' or 'Plasticity' --------------------	
# psb2 is the visualisation and analyisis tool for P-matrices
# it uses the rgl() function and libarary, so will require xquarts on a mac

# must specify the models, the number of traits, the method = "P"
# and various other things linked to annnotation by RGL package
# axes.lab = TRUE plots the loadings from the 'PCA' onto the 3 axes as labels

# output in R inlcudes test of plasticity (SHIFT IN CENTROID)
# output in R includes loadings on PC1-3 axis
# output in R includes estimate of variance on PC1-3 in E1 and in E2

psb2(model4.1P.1, model4.2P.1, no.traits = 5, method = "P", axes.lab = TRUE)


## Example Stops, raw datas and models below ----




## data generation and model code provided here for reference ----
# All data and models are loaded above via .RData files

	# ## Generate data for multiple traits ----------------------------------------------------
	# # involves defining the gmatrix and then simulating data with variance
	# 
	# 
	# 
	# ## Example 1 Data: comparison between two matrices that are similar ----
	# ## but there is a change in variance for one of the matrices
	# ## i.e in one environment everything is integrated, but in 
	# ## another there is divergence
	# 
	# # All relationships highly positive between four traits measured 
	# # across two environments (8x8 matrix)
	# 
	# G_1<-matrix(c(
	#   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   0.8,   1.0),10,10) 
	# 
	# # NOTE IN THIS SCRIPT WE HAVE ALL TRAITS IN E1 at ~-5 and all traits in E2 at ~5
	# # generated via residuals with a mean
	# 
	# bv_1 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_1)
	# sire1<-lapply(bv_1, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# 	res1=rnorm(800,-6,1.35^2),
	# 	res2=rnorm(800,-5,1.35^2),
	# 	res3=rnorm(800,-4,1.35^2),
	# 	res4=rnorm(800,-4.5,1.35^2),
	# 	res5=rnorm(800,-5.5,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,4,1.35^2),
	# 	res8=rnorm(800,6,1.35^2),
	# 	res9=rnorm(800,4.5,1.35^2),
	# 	res10=rnorm(800,6.5,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# 
	# data1<-lapply(sire1, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	# 
	# # Example 2 Data: Relationships between traits constant within an environment but ----
	# # are negative across environments
	# 
	# G_2<-matrix(c(
	#   1.0,   0.8,   0.8,   0.8,   0.8,  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,
	#   0.8,   1.0,   0.8,   0.8,   0.8,  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,
	#   0.8,   0.8,   1.0,   0.8,   0.8,  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,
	#   0.8,   0.8,   0.8,   1.0,   0.8,  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,
	#   0.8,   0.8,   0.8,   0.8,   1.0,  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,
	#  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,   1.0,   0.8,   0.8,   0.8,   0.8
	#  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,   0.8,   1.0,   0.8,   0.8,   0.8,
	#  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,   0.8,   0.8,   1.0,   0.8,   0.8,
	#  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,   0.8,   0.8,   0.8,   1.0,   0.8,  
	#  -0.8,  -0.8,  -0.8,  -0.8,  -0.8,   0.8,   0.8,   0.8,   0.8,   1.0),10,10) 
	# 
	# bv_2 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_2)
	# sire2<-lapply(bv_2, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# 	res1=rnorm(800,-6,1.35^2),
	# 	res2=rnorm(800,-5,1.35^2),
	# 	res3=rnorm(800,-4,1.35^2),
	# 	res4=rnorm(800,-4.5,1.35^2),
	# 	res5=rnorm(800,-5.5,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,4,1.35^2),
	# 	res8=rnorm(800,6,1.35^2),
	# 	res9=rnorm(800,4.5,1.35^2),
	# 	res10=rnorm(800,6.5,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# data2<-lapply(sire2, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	# 
	# # Example 3 Data: One vector in environment 1, two vectors in environments 2 ----
	# # and relationships between traits reduce. 
	# 
	# G_3<-matrix(c(
	#   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.6,   0.4,   0.2,   0.0,
	#   0.6,   0.6,   0.6,   0.6,   0.6,   0.6,   1.0,   0.4,   0.2,   0.0,
	#   0.4,   0.4,   0.4,   0.4,   0.4,   0.4,   0.4,   1.0,   0.2,   0.0,
	#   0.2,   0.2,   0.2,   0.2,   0.2,   0.2,   0.2,   0.2,   1.0,   0.0,
	#   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1.0),10,10) 
	# 
	# bv_3 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_3)
	# sire3<-lapply(bv_3, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# res1=rnorm(800,-6,1.35^2),
	# 	res2=rnorm(800,-5,1.35^2),
	# 	res3=rnorm(800,-4,1.35^2),
	# 	res4=rnorm(800,-4.5,1.35^2),
	# 	res5=rnorm(800,-5.5,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,4,1.35^2),
	# 	res8=rnorm(800,6,1.35^2),
	# 	res9=rnorm(800,4.5,1.35^2),
	# 	res10=rnorm(800,6.5,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# data3<-lapply(sire3, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	# 
	# 
	# 
	# # Example 4 Data: One vector in environment 1, two vectors in environments 2 ----
	# # and relationships between traits reduce. Higher variation
	# # in environment 2 
	# 
	# G_4<-matrix(c(
	#   1.0,   0.8,   0.8,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   1.0,   0.8,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   1.0,   0.8,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   1.0,   0.8,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   0.8,   1.0,   0.8,   0.6,   0.4,   0.2,   0.0,
	#   0.8,   0.8,   0.8,   0.8,   0.8,   1.0,   0.6,   0.4,   0.2,   0.0,
	#   0.6,   0.6,   0.6,   0.6,   0.6,   0.6,   1.5,   0.8,   0.4,   0.2,
	#   0.4,   0.4,   0.4,   0.4,   0.4,   0.4,   0.8,   2.0,   1.0,   0.4,
	#   0.2,   0.2,   0.2,   0.2,   0.2,   0.2,   0.4,   1.0,   2.5,   1.2,
	#   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.2,   0.4,   1.2,   3.0),10,10) 
	# 
	# bv_4 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_4) # 2.7.12 found this to be G_3 .... hmmm..... changed to G_4
	# sire4<-lapply(bv_4, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# res1=rnorm(800,-6,1.35^2),
	# 	res2=rnorm(800,-5,1.35^2),
	# 	res3=rnorm(800,-4,1.35^2),
	# 	res4=rnorm(800,-4.5,1.35^2),
	# 	res5=rnorm(800,-5.5,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,4,1.35^2),
	# 	res8=rnorm(800,6,1.35^2),
	# 	res9=rnorm(800,4.5,1.35^2),
	# 	res10=rnorm(800,6.5,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# data4<-lapply(sire4, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	# 
	# # Example 4.1 Data: a more creative phenotype for visualisation ----
	# #-5,-2,-1,-2,-3,5,-7,2,1,4
	# 
	# bv_4.1 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_3)
	# sire4.1<-lapply(bv_4, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# res1=rnorm(800,-5,1.35^2),
	# 	res2=rnorm(800,-2,1.35^2),
	# 	res3=rnorm(800,-1,1.35^2),
	# 	res4=rnorm(800,-2,1.35^2),
	# 	res5=rnorm(800,-3,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,-7,1.35^2),
	# 	res8=rnorm(800,2,1.35^2),
	# 	res9=rnorm(800,1,1.35^2),
	# 	res10=rnorm(800,4,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# data4.1<-lapply(sire4.1, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	# 
	# # Example 5 Data: Two vectors in environment 1, two vectors in environments 2 ----
	# # and relationships between traits reduce. Higher variation
	# # in environment 2 
	# 
	# G_5<-matrix(c(
	#   1.0,   0.6,   0.4,   0.2,   0.0,  -0.8,  -0.6,  -0.4,  -0.2,   0.0,
	#   0.6,   1.0,   0.6,   0.4,   0.2,  -0.6,  -0.8,  -0.6,  -0.4,  -0.2,
	#   0.4,   0.6,   1.0,   0.6,   0.4,  -0.4,  -0.6,  -0.8,  -0.6,  -0.4,
	#   0.2,   0.4,   0.6,   1.0,   0.6,  -0.2,  -0.4,  -0.6,  -0.8,  -0.6,
	#   0.0,   0.2,   0.4,   0.6,   1.0,   0.0,  -0.2,  -0.4,  -0.6,  -0.8,
	#  -0.8,  -0.6,  -0.4,  -0.2,   0.0,   1.0,   0.6,   0.4,   0.2,   0.0,
	#  -0.6,  -0.8,  -0.6,  -0.4,  -0.2,   0.6,   1.5,   1.0,   0.4,   0.2,
	#  -0.4,  -0.6,  -0.8,  -0.6,  -0.4,   0.4,   1.0,   2.0,   1.2,   0.4,
	#  -0.2,  -0.4,  -0.6,  -0.8,  -0.6,   0.2,   0.4,   1.2,   2.5,   1.4,
	#   0.0,  -0.2,  -0.4,  -0.6,  -0.8,   0.0,   0.2,   0.4,   1.4,   3.0),10,10)
	# 
	# bv_5 <- lapply(1, mvrnorm, n=200, mu=rep(0,10), Sigma=G_5)
	# sire5<-lapply(bv_5, function(x) data.frame(sire=rep(1:nrow(x),each=4), rpt=rep(1:4,nrow(x)),
	# res1=rnorm(800,-6,1.35^2),
	# 	res2=rnorm(800,-5,1.35^2),
	# 	res3=rnorm(800,-4,1.35^2),
	# 	res4=rnorm(800,-4.5,1.35^2),
	# 	res5=rnorm(800,-5.5,1.35^2),
	# 	res6=rnorm(800,5,1.35^2),
	# 	res7=rnorm(800,4,1.35^2),
	# 	res8=rnorm(800,6,1.35^2),
	# 	res9=rnorm(800,4.5,1.35^2),
	# 	res10=rnorm(800,6.5,1.35^2), 
	# 	bv1=rep(x[,1],each=4),bv2=rep(x[,2],each=4),bv3=rep(x[,3],each=4),bv4=rep(x[,4],each=4),bv5=rep(x[,5],each=4),
	# 	bv6=rep(x[,6],each=4),bv7=rep(x[,7],each=4),bv8=rep(x[,8],each=4),bv9=rep(x[,9],each=4),bv10=rep(x[,10],each=4)))
	# data5<-lapply(sire5, function(x) cbind(x, trait1=x$res1+x$bv1, trait2=x$res2+x$bv2, trait3=x$res3+x$bv3,trait4=x$res4+x$bv4,trait5=x$res5+x$bv5,trait6=x$res6+x$bv6,trait7=x$res7+x$bv7,trait8=x$res8+x$bv8,trait9=x$res9+x$bv9,trait10=x$res10+x$bv10))
	
	## All models have been run and are loaded via .RData ------------
	
	# ## Run the models for each data frame
	# 
	# prior1<-list(R=list(V=diag(5)*0.02, nu=6))
	# 
	# model1.1P<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1,rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data1[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model1.2P<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data1[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	# model2.1P<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data2[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model2.2P<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data2[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	# model3.1P<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data3[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model3.2P<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data3[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	# model4.1P<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data4[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model4.2P<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data4[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	# model5.1P<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data5[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model5.2P<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1,rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data5[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	# model4.1P.1<-MCMCglmm(cbind(trait1, trait2, trait3, trait4, trait5)  ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data4.1[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# model4.2P.1<-MCMCglmm(cbind(trait6, trait7, trait8, trait9, trait10) ~ trait-1, rcov=~us(trait):units, family=c("gaussian","gaussian","gaussian","gaussian", "gaussian"), prior=prior1, data=data4.1[[1]], verbose=FALSE, burnin=50000, thin=100, nitt=150000)
	# 
	